install.packages("inlinedocs",repos="http://r-forge.r-project.org")
library(inlinedocs)
f <- system.file("testfiles/fermat.R",package="inlinedocs")
test.file(f)
fermat <- file.path(tempdir(),"fermat")
package.skeleton.dx(fermat)
