2011-06-09-HOCKING-R-Forge.pdf: 2011-06-09-HOCKING-R-Forge.tex
	pdflatex 2011-06-09-HOCKING-R-Forge
	pdflatex 2011-06-09-HOCKING-R-Forge
2011-06-09-HOCKING-R-Forge.tex: 2011-06-09-HOCKING-R-Forge.Rnw
	bash -c 'echo $$PATH'
	which R
	Rscript -e 'knitr::knit("2011-06-09-HOCKING-R-Forge.Rnw")'
