2011-06-09-HOCKING-development.pdf: 2011-06-09-HOCKING-development.Rnw
	bash -c 'echo $$PATH'
	which R
	R CMD pgfsweave 2011-06-09-HOCKING-development.Rnw
# 2011-06-09-HOCKING-development.pdf: 2011-06-09-HOCKING-development.tex 
# 	pdflatex 2011-06-09-HOCKING-development
# 2011-06-09-HOCKING-development.tex: 2011-06-09-HOCKING-development.Rnw project.stats.csv project.users.csv
# 	R CMD Sweave 2011-06-09-HOCKING-development.Rnw
